### ISSUE TITLE
Setup Autobahn Websocket Tests

### ISSUE THREAD

**Issue by maclover7** [mironrb/miron#22]
[Autobahn](autobahn.ws/testsuite/) is a tool that lets you test and see if your websockets implementation is RFC-compliant. [Faye](https://github.com/faye/wstest) currently uses this, among other OSS projects. Definitely something we want to think about adding in the future.

Helpful links:
- [Autobahn website](autobahn.ws/testsuite/)
-Since the project is written in Python, we'll need a .travis.yml file that looks something like this:
```yaml
language: 
  - python
python:
  - "2.7"
before_script:
  - rvm install 2.2.3
  - pip install autobahntestsuite
  - pip install unittest2
script: wstest --help

matrix:
  include:
  - python: "2.7"
    rvm: 2.2.2
```
